version: '3.5'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
      - ./security/certbot/conf:/etc/letsencrypt
      - ./security/certbot/www:/var/www/certbot
    depends_on:
      - cvbackend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./security/certbot/conf:/etc/letsencrypt
      - ./security/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  cvbackend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: cvbackend
    expose:
      - "8000"
    volumes:
      - static_volume:/home/cvbackend/web/static
      - media_volume:/home/cvbackend/web/media
    image: cvbackendimage
    restart: on-failure

volumes:
  static_volume:
  media_volume:
